name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
     - uses: actions/checkout@v3
     - run: sudo apt update
     - run: sudo apt install nasm gcc

     - name: Make the project
       run: make
  
