name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install depedencies
      uses: actions/checkout@v3
      run: sudo apt update
      run: sudo apt install nasm
    
    - name: Make the project
      run: make

    -name: Clean all the files
      run: make clean
      
